name: CI Rust testing

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo build --verbose
      - run: cargo test --verbose

  publish:
    name: Publish to crates.io
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Publish
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: >
          cargo publish
          --dry-run
          --verbose
          --locked
          --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
    